#Chapter 8 of the Official Python 3.13 tutorial

#   * 8. Errors and Exceptions

#  * 8.1. Syntax Errors
#  * 8.2. Exceptions
#  * 8.3. Handling Exceptions
#  * 8.4. Raising Exceptions
#  * 8.5. Exception Chaining
#  * 8.6. User-defined Exceptions
#  * 8.7. Defining Clean-up Actions
#  * 8.8. Predefined Clean-up Actions
#  * 8.9. Raising and Handling Multiple Unrelated Exceptions
#  * 8.10. Enriching Exceptions with Notes

def hello():
    print("hello")


hello() 



# the compiler has basic error and exception detecting


# 8.3. Handling Exceptions
# while True:
#     try:
#         x = int(input("Please enter a number: "))
#         break
#     except ValueError:
#         print("Oops!  That was no valid number.  Try again...")


# sections skipped:
 # * 8.4. Raising Exceptions
 # * 8.5. Exception Chaining
 # * 8.6. User-defined Exceptions
 # * 8.7. Defining Clean-up Actions
 # * 8.8. Predefined Clean-up Actions
 # * 8.9. Raising and Handling Multiple Unrelated Exceptions
 # * 8.10. Enriching Exceptions with Notes




